# timeouts
max_redirects = 5
timeout = 20

# don’t fail on flaky externals
exclude_all_private = false
accept = ["200..299", "300..399"]
retry_wait_time = 2
max_retries = 2

# ignore known dynamic or gated links
exclude = [
  "mailto:*",
  "https://buy.stripe.com/*",
  "https://the-grid111.github.io/*" # self links resolve after deploy
]

# output a small report
format = "markdown"
output = "lychee/out.md"
