# Ignore all external links; validate only internal repo paths.
exclude = ["^https?://", "^mailto:", "^tel:"]
# Skip common directories
exclude_path = [".github", "node_modules"]
# Be gentle with CI
max_concurrency = 8
retry_wait_time = 2
max_retries = 2
# Accept typical OK/redirect statuses (for local files this is moot)
accept = ["200..399"]
