name: Asset Manifest Bump

on:
  push:
    branches: [ main ]
    paths:
      - 'assets/**'
      - '!assets/manifest.json'  # will be rewritten by this job
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate manifest
        run: node scripts/bump-asset-manifest.mjs

      - name: Commit manifest if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(assets): bump manifest (auto)"
          file_pattern: assets/manifest.json
