name: Build File Inventory
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate file inventory
        run: node dev/scripts/gen-file-inventory.mjs

      - name: Commit file inventory
        run: |
          git config user.name "grid-bot"
          git config user.email "grid-bot@users.noreply.github.com"
          git add dev/data/file-tree.*
          git commit -m "chore: update file inventory" || echo "No changes"
          git push
