name: Build File Inventory

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dev/dev/archive/**'
      - 'dev/dev/data/file-tree.json'
      - 'dev/dev/data/file-tree.txt'
      - 'dev/dev/data/repo-metrics.json'
      - 'dev/dev/state_packs/**'

jobs:
  inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Generate file inventory
        run: |
          mkdir -p dev/dev/data
          # Only inventory "real" project files, exclude generated telemetry
          git ls-files \
            ':(exclude)dev/dev/archive/**' \
            ':(exclude)dev/dev/data/file-tree.json' \
            ':(exclude)dev/dev/data/file-tree.txt' \
            ':(exclude)dev/dev/data/repo-metrics.json' \
            ':(exclude)dev/dev/state_packs/**' \
          > dev/dev/data/file-tree.txt

          # Convert to JSON
          jq -R -s -c 'split("\n")[:-1]' dev/dev/data/file-tree.txt > dev/dev/data/file-tree.json

      - name: Commit inventory
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dev/dev/data/file-tree.*
          git commit -m "Update file inventory [skip ci]" || echo "No changes"
          git push
