name: Auto Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# 👇 This prevents two deploys running at the same time
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Configure Pages build
      - name: Setup Pages
        uses: actions/configure-pages@v4

      # Upload the site (root folder). If your site lives in /dist, set path: dist
      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      # Deploy and WAIT until GitHub Pages finishes
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
