name: Link Check
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.html'
      - 'lychee.toml'
permissions:
  contents: read
jobs:
  lychee:
    runs-on: ubuntu-latest
    continue-on-error: true   # hygiene, never blocks deploy
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --config lychee.toml
            --max-concurrency 6
            --exclude-mail
            --no-progress
            .
      - name: Upload lychee report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: lychee/out.md
