name: Link Check
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lychee (internal links only)
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          # Respect lychee.toml (ignores external links)
          args: --config lychee.toml --no-progress .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
