name: Apply patch
on:
  issue_comment:
    types: [created]
permissions:
  contents: write
  issues: write

jobs:
  patch:
    if: startsWith(github.event.comment.body, '/patch ')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract command
        id: parse
        run: |
          CMD="${{ github.event.comment.body }}"
          echo "cmd=$CMD" >> $GITHUB_OUTPUT

      - name: Apply patch
        run: |
          LINE="${{ steps.parse.outputs.cmd }}"
          FILE=$(echo "$LINE" | sed -n 's/.*path=\([^ ]*\).*/\1/p')
          SEARCH=$(echo "$LINE" | sed -n 's/.*search=\"\([^"]*\)\".*/\1/p')
          REPLACE=$(echo "$LINE" | sed -n 's/.*replace=\"\([^"]*\)\".*/\1/p')

          echo "File: $FILE"
          echo "Search: $SEARCH"
          echo "Replace: $REPLACE"

          if [ ! -f "$FILE" ]; then
            echo "::error::File not found: $FILE"
            exit 1
          fi

          sed -i "s|$SEARCH|$REPLACE|g" "$FILE"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "patch applied from issue comment" || echo "no changes"
          git push
