name: Repo Hygiene
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  json-valid:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate all JSON (except lock/manifests we write)
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=$(git ls-files '*.json' ':!package-lock.json')
          for f in $files; do
            echo "Checking $f"
            jq -e . "$f" >/dev/null || { echo "::error file=$f::Invalid JSON"; exit 1; }
          done

  whitespace:
    name: Trailing whitespace (warn only)
    runs-on: ubuntu-latest
    continue-on-error: true   # never blocks deploys
    steps:
      - uses: actions/checkout@v4
      - name: Scan for trailing whitespace
        run: |
          set -euo pipefail
          bad=$(git ls-files | xargs -I{} grep -nE "[[:blank:]]+$" "{}" || true)
          if [ -n "$bad" ]; then
            echo "$bad" | sed 's/^/::warning::Trailing whitespace -> /'
          else
            echo "No trailing whitespace"
          fi

  svg-sanity:
    name: SVG sanity check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '18' }
      - name: Run SVG sanity
        run: node scripts/svg-sanity.mjs
