name: Repo Hygiene

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  hygiene:
    runs-on: ubuntu-latest
    # Keep runs green; report warnings in logs only
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Basic hygiene report
        run: |
          echo "== Large files (>10MB) =="
          find . -type f -size +10M -not -path "./.git/*" -printf "%P (%k KB)\n" || true
          echo
          echo "== Trailing spaces (first 50 hits) =="
          grep -RIl --exclude-dir=.git --exclude-dir=node_modules ' $' | head -n 50 || true
          echo
          echo "== CRLF files (first 50 hits) =="
          git ls-files -z | xargs -0 file | grep CRLF | head -n 50 || true
