name: Repo Snapshot

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate repo snapshot
        run: node scripts/repo-snapshot.mjs

      - name: Commit snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update repo snapshot"
          branch: main
          file_pattern: |
            dev/data/file-tree.*
            dev/data/repo-metrics.json
