name: Repo Snapshot

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Keep Node consistent & also re-run apply to guarantee snapshot sees latest edits
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Apply update.json ops (idempotent)
        run: node scripts/apply-update.mjs

      - name: Make archive dir
        run: mkdir -p dev/dev/archive

      - name: Write snapshot JSON
        run: |
          node - <<'NODE'
          import fs from 'node:fs';
          import path from 'node:path';
          const outDir = 'dev/dev/archive';
          const ts = Math.floor(Date.now()/1000);
          const sha = process.env.GITHUB_SHA || '';
          function walk(dir='.') {
            let files = [];
            for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
              const rel = path.posix.join(dir, e.name).replace(/^\.\//,'');
              if (rel.startsWith('.git/') || rel.startsWith('node_modules/')) continue;
              if (e.isDirectory()) files = files.concat(walk(rel));
              else files.push(rel);
            }
            return files.sort();
          }
          const files = walk('.');
          const items = files.map(p => ({ path: p, bytes: fs.statSync(p).size }));
          const snapshot = {
            type: "repo-snapshot",
            createdAt: new Date().toISOString(),
            ts, sha,
            count: items.length,
            items
          };
          const out = path.join(outDir, `snapshot_${ts}.json`);
          fs.writeFileSync(out, JSON.stringify(snapshot, null, 2));
          console.log("wrote", out, "items:", items.length);
          NODE

      - name: Auto-commit snapshot
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Repo snapshot (auto)"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          file_pattern: dev/dev/archive/snapshot_*.json
