name: Repo Hygiene
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - "assets/**/*.json"
      - "assets/**/*.svg"
      - "assets/manifest.json"
      - "assets/images/**"
      - "scripts/*.mjs"
permissions:
  contents: read
jobs:
  json:
    name: JSON sanity
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node scripts/check-json.mjs || echo "::warning ::JSON check reported issues"

  svg:
    name: SVG sanity
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - run: node scripts/svg-sanity.mjs || echo "::warning ::SVG check reported issues"

  bump:
    name: Asset manifest (noop-safe)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Run bump script if present
        run: |
          if [ -f scripts/bump-asset-manifest.mjs ]; then
            node scripts/bump-asset-manifest.mjs || echo "::warning ::bump script warnings"
          else
            echo "no bump script; skipping"
          fi
