name: SVG Sanity

on:
  push:
    branches: [ main ]
    paths:
      - 'assets/images/**/*.svg'
      - 'favicon.svg'
  workflow_dispatch:

jobs:
  svgcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Sanity check SVGs
        run: node scripts/svg-sanity.mjs
